learning_templates/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

#Templete tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^relative/$',views.relative,name='relative'),
    url(r'^other/$',views.other,name='other'),
]

learning_templates/learning_templates/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/',include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict={'text':'Hello world','number':100}
    return render(request,'basic_app/index.htm',context_dict)

def other(request):
    return render(request,'basic_app/other.htm')

def relative(request):
    return render(request,'basic_app/relative_url_template.htm')

learning_templates/basic_app/templates/basic_app/basic.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Document</title>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li><a class="navbar-link" href="{% url 'admin:index' %}">ADMIN</a></li>
                <li><a class="navbar-link" href="{% url 'basic_app:other' %}">OTHER</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {%  block body_block %}
        <!-- any thing in this block -->
        {% endblock %}
    </div>
</body>
</html>

learning_templates/basic_app/templates/basic_app/index.htm
<!DOCTYPE html>
{% extends "basic_app/basic.htm"%}
    {% block body_block %}

    <br>

       <h1> {{ text|cut:'world' }} </h1>
       <h1> {{ number|add:"99" }}</h1>


    <br>
    <br>
        <h1>WELCOME TO INDEX</h1>
        <h1>THIS IS AN EXAMPLE OF TEMPLATE INHERITANCE!</h1>
    {% endblock %}

learning_templates/basic_app/templates/basic_app/other.htm
<!DOCTYPE html>
{% extends "basic_app/basic.htm"%}
    {% block body_block %}
        <h1>WELCOME TO OTHER PAGE</h1>
        <a href="{% url 'index' %}">THE INDEX PAGE</a><br>
        <a href="{% url 'basic_app:relative' %}">THE RELATIVE PAGE</a><br>
        <a href="{% url 'admin:index' %}">ADMIN</a>
        <h1>THIS IS AN EXAMPLE OF TEMPLATE INHERITANCE!</h1>
    {% endblock %}

learning_templates/basic_app/templates/basic_app/relative_url_template.htm
<!DOCTYPE html>
{% extends "basic_app/basic.htm"%}
    {% block body_block %}
        <h1>WELCOME TO RELATIVE URL TEMPLATE PAGE</h1>
        <h1>THIS IS AN EXAMPLE OF TEMPLATE INHERITANCE!</h1>
    {% endblock %}